### ISSUE TITLE
Add `.champion` to complement `.champion_id`

### ISSUE THREAD

**Issue by PeterBorah** [PeterBorah/vigor#18]
We have real Champion objects, so let's use them! Calling `.champion` on a game/summoner/etc. should retrieve the full Champion object from the ID.

**Comment by imogenkinsman** [comment]
Hm, champion data doesn't change much (other than free-to-play cycling weekly). If we want to grab champion objects like this, I'm thinking it might make sense to save the self.all_champions response in the client, or we'd need an API call every time we want champions info. Gonna sleep on it, but wouldn't be too hard to do.

**Comment by PeterBorah** [comment]
Yeah, agreed. Pulling it every time feels bad, but at the same time, it's not _completely_ static data. (Other things beyond free-to-play might change as balance changes are made, new champions are released, etc.) Not sure what the best solution is.
