### ISSUE TITLE
Finding a Champion based on its ID.

### ISSUE THREAD

**Issue by chrisroman** [PeterBorah/vigor#22]
Sort of a nuisance trying to find out who played what champ in a game because a game is returning the champion's id, not their name. I'm not sure if you already support finding a champion by its id, but here's what I suggest.

def self.champion(lookup_value)
        if lookup_value.is_a? String
                self.all_champions.find {|champ| champ.name == lookup_value}
        else
                self.all_champions.find {|champ| champ.id == lookup_value}
        end
end

P.S. I'm pretty new to all of this stuff so if this was just a waste of time, sorry :(
Edit: I have no clue how to use github's flavored markdown so it looks all bad

**Comment by PeterBorah** [comment]
Good idea! We're working on making it even easier than that to get the champion (see #18), but this is definitely a good change to make either way.

**Comment by imogenkinsman** [comment]
@RedSevens Totally agree - this is next on my list. Thanks!

@PeterBorah I'm on vacation and don't have my machine here >< will try to keep up with completing issues.

**Comment by PeterBorah** [comment]
> I'm on vacation and don't have my machine here >< will try to keep up with completing issues.

Hey, don't worry about it! You don't have any obligation to do anything for this project, much less with any sort of deadline. :P
