### ISSUE TITLE
Exception when loading Game History including Bot

### ISSUE THREAD

**Issue by gctom57** [PeterBorah/vigor#30]
I got an 

```
undefined method `map' for nil:NilClass
```

when trying to list all recent game for my summoner but I saw that you don't check wether it was a bot game or with other player.

This issue is that when the game include only bot, the hash fellowPlayers is empty and so the line

```
@fellow_players = data["fellowPlayers"].map { |player| Summoner.new(player, :game) }
```

create the exception.

I'm very new to ruby but thanks to RubyMine I was able to fix this issue on my side : 

```
if !data["fellowPlayers"].nil?
    @fellow_players = data["fellowPlayers"].map { |player| Summoner.new(player, :game) }
end
```

but there may be a better solution for that

**Comment by imogenkinsman** [comment]
There's been a few other issues with empty response fields not being adequately handled. I'll look into this when I'm back home (and try to test out some more edge cases too). I suspect this might be impacting solo custom games too. Thanks!

edit: yeep, replicated the bug, thanks again
