### ISSUE TITLE
Refactor tests to not hit the API so often

### ISSUE THREAD

**Issue by PeterBorah** [PeterBorah/vigor#4]
We should have at least few tests that actually check the connection to Riot's servers, but we shouldn't hit the servers for every test. The current pattern is unsustainable, because of rate limiting, and also just the slowness of making API calls with every test. Also, I don't want to break the test by changing my masteries. :P

We should investigate gems like webmock and vcr, and find a sustainable pattern that still gives us realistic tests.

**Comment by imogenkinsman** [comment]
Looking into this - the tests are going to start exhausting our API calls as they grow, so mocking is probably going to be necessary.
