### ISSUE TITLE
Access to runes/masteries/etc. shouldn't require a superfluous API call

### ISSUE THREAD

**Issue by PeterBorah** [PeterBorah/vigor#6]
At the moment, the natural path for getting to someone's masteries (or runes, or in the future other things) is to instantiate a `Summoner` object with `vigor.summoner(id)`, and then call `.mastery_pages` on it. This will create two API calls, regardless of whether you care about the summoner information. There should be a straightforward, intuitive way to get masteries without having to to load the summoner first.

**Comment by imogenkinsman** [comment]
Is this still an issue? Vigor has self.rune_pages and self.mastery_pages, so it's no longer necessary to create a summoner unless you need to look up their ID.

**Comment by PeterBorah** [comment]
Yep, good call. I fixed this a few weeks ago, but forgot to close the issue.

**Comment by PeterBorah** [comment]
See 26081ea1911f0790c37f0ceb6ebbb08b44cb6e59.
